---
  - name: "show remote environment"
    shell: env

  - name: Copy backend files
    become: true
    copy:
      src: /home/backend.tar.gz
      dest: /home/ubuntu/uda_app/backend.tar.gz

  - name: "copy backend binaries"
    become: yes
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/uda_app
      recursive: true

#  - name: "copy backend file"
#    become: true
#    copy:
#      src: /root/project/backend
#      dest: /home/ubuntu/uda_app
#      force: no

#  - name: "copy node_modules"
#    become: true
#    synchronize:
#      src: /root/project/backend/
#      dest: /home/ubuntu/uda_app
#      recursive: true

  - name: "Extract tar"
    become: true
    command:
      /home/ubuntu/uda_app/backend.tar.gz -C /home/ubuntu/uda_app/

  - name: "Check"
    become: true
    command:
      ls -l /home/ubuntu/uda_app/backend

  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true

  - name: "start server"
    become: true
    command: pm2 start -f ./main.js
    args:
      chdir: /home/ubuntu/uda_app/dist
    environment:
     ENVIRONMENT: production
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./migrations"
     TYPEORM_MIGRATIONS: "./migrations/*.js"
     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"